ALTER TABLE products ADD COLUMN IF NOT EXISTS mrp NUMERIC(12, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS selling_price NUMERIC(12, 2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS weight NUMERIC(10, 3);
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT;
