import { ArrowLeftIcon, BanIcon, DownloadIcon, PrinterIcon, QrCodeIcon } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { PageContainer, PageDescription, PageHeader, PageHeading, PageLayout, PageTitle } from '@/components/layout/page-layout'
import { demoQRs } from './qr-data'
import { QRPreview } from './qr-preview'

function QRCodeDetailsPage() { const { id } = useParams(); const item = demoQRs.find((qr) => qr.id === id) ?? demoQRs[0]
  return <PageLayout className="bg-[#F7F8FA]"><PageContainer><div className="space-y-6 pb-10"><Link to="/qrcodes" className="inline-flex h-9 items-center gap-2 rounded-lg px-3 text-sm font-medium text-muted-foreground hover:bg-secondary"><ArrowLeftIcon /> Back to QR codes</Link><PageHeader><PageHeading><PageTitle>QR Code details</PageTitle><PageDescription>{item.qrToken}</PageDescription></PageHeading><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm"><DownloadIcon /> PNG</Button><Button variant="outline" size="sm"><DownloadIcon /> SVG</Button><Button variant="outline" size="sm"><PrinterIcon /> Print</Button><Button variant="outline" size="sm"><BanIcon /> Deactivate</Button></div></PageHeader><div className="grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]"><Card><CardContent className="flex min-h-80 items-center justify-center"><QRPreview token={item.qrToken} size="lg" /></CardContent></Card><Card><CardHeader><CardTitle>Traceability information</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-2"><Info label="QR ID" value={item.qrToken} /><Info label="Product" value={item.productName} /><Info label="Batch" value={item.batchNumber} /><Info label="Manufacturing date" value={item.manufacturingDate} /><Info label="Expiry date" value={item.expiryDate} /><Info label="Created date" value={item.createdDate} /><div><p className="text-xs text-muted-foreground">Status</p><Badge className="mt-1" variant={item.status === 'Active' ? 'success' : 'secondary'}>{item.status}</Badge></div></CardContent></Card></div><div className="grid gap-5 sm:grid-cols-3"><Metric icon={QrCodeIcon} label="Total scans" value={String(item.scanCount)} /><Metric icon={PrinterIcon} label="Last scan" value={item.lastScan ?? 'Never'} /><Metric icon={QrCodeIcon} label="QR format" value="Traceability" /></div></div></PageContainer></PageLayout> }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div> }
function Metric({ icon: Icon, label, value }: { icon: typeof QrCodeIcon; label: string; value: string }) { return <Card><CardContent className="p-5"><Icon className="size-5 text-primary" /><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 truncate font-heading text-lg font-bold">{value}</p></CardContent></Card> }
export default QRCodeDetailsPage
