import { useEffect, useState } from 'react'
import { ArrowLeftIcon, BarChart3Icon, HeartIcon, MessageSquareTextIcon, PackageIcon, QrCodeIcon, ShieldAlertIcon } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { EmptyState } from '@/components/common/empty-state'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { PageContainer, PageDescription, PageHeader, PageHeading, PageLayout, PageTitle } from '@/components/layout/page-layout'
import { API_URL } from '@/context/auth-context'
import type { ProductRecord } from './product-data'

function ProductDetailsPage() { const { id } = useParams(); const [product, setProduct] = useState<ProductRecord | null>(null); useEffect(() => { void fetch(`${API_URL}/products/${id}`, { credentials: 'include' }).then((response) => response.ok ? response.json() : null).then((item: { id: string; name: string; sku: string; category?: { name?: string } | null; sellingPrice?: string | number | null; mrp?: string | number | null; isActive: boolean; createdAt: string; batches?: Array<{ quantity: number }> } | null) => { if (item) setProduct({ id: item.id, name: item.name, sku: item.sku, category: item.category?.name ?? 'Uncategorized', price: `₹${item.sellingPrice ?? item.mrp ?? '—'}`, stock: item.batches?.reduce((sum, batch) => sum + batch.quantity, 0) ?? 0, status: item.isActive ? 'Active' : 'Archived', qrGenerated: 0, createdDate: new Date(item.createdAt).toLocaleDateString('en-IN'), image: '🌾' }) }) }, [id]); if (!product) return <PageLayout className="bg-[#F7F8FA]"><PageContainer><Link to="/products" className="inline-flex h-9 items-center gap-2 rounded-lg px-3 text-sm font-medium text-muted-foreground hover:bg-secondary"><ArrowLeftIcon /> Back to products</Link><EmptyState className="mt-6" title="Product not found" description="This product is not available in the PostgreSQL catalog." /></PageContainer></PageLayout>
  return <PageLayout className="bg-[#F7F8FA]"><PageContainer><div className="space-y-6 pb-10"><Link to="/products" className="inline-flex h-9 items-center gap-2 rounded-lg px-3 text-sm font-medium text-muted-foreground hover:bg-secondary hover:text-foreground"><ArrowLeftIcon /> Back to products</Link><PageHeader><PageHeading><PageTitle>{product.name}</PageTitle><PageDescription>{product.sku} · {product.category}</PageDescription></PageHeading></PageHeader><div className="grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]"><Card><CardContent className="flex h-full min-h-64 items-center justify-center"><span className="text-7xl">{product.image}</span></CardContent></Card><Card><CardHeader><CardTitle>Product information</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Info label="SKU" value={product.sku} /><Info label="Price" value={product.price} /><Info label="Category" value={product.category} /><Info label="Stock" value={product.stock.toLocaleString()} /><div><p className="text-xs text-muted-foreground">Status</p><Badge className="mt-1" variant={product.status === 'Active' ? 'success' : 'secondary'}>{product.status}</Badge></div><Info label="Created date" value={product.createdDate} /></CardContent></Card></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={PackageIcon} label="Batch details" value="Database batches" /><Metric icon={QrCodeIcon} label="QR count" value={String(product.qrGenerated)} /><Metric icon={BarChart3Icon} label="Total scans" value="0" /><Metric icon={MessageSquareTextIcon} label="Feedback count" value="0" /><Metric icon={ShieldAlertIcon} label="Complaints" value="0" /><Metric icon={HeartIcon} label="Compliments" value="0" /></div><Card><CardHeader><CardTitle>Nutrition</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Nutrition information will be available once the product profile is completed.</CardContent></Card></div></PageContainer></PageLayout> }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div> }
function Metric({ icon: Icon, label, value }: { icon: typeof PackageIcon; label: string; value: string }) { return <Card><CardContent className="p-5"><Icon className="size-5 text-primary" /><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 truncate font-heading text-lg font-bold">{value}</p></CardContent></Card> }
export default ProductDetailsPage
