"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.qrCodeRoutes = void 0;
const express_1 = require("express");
const qrcode_controller_js_1 = require("../controllers/qrcode-controller.js");
exports.qrCodeRoutes = (0, express_1.Router)();
exports.qrCodeRoutes.get('/', qrcode_controller_js_1.qrCodeController.list);
exports.qrCodeRoutes.get('/download', qrcode_controller_js_1.qrCodeController.download);
exports.qrCodeRoutes.get('/print', qrcode_controller_js_1.qrCodeController.print);
exports.qrCodeRoutes.get('/:id', qrcode_controller_js_1.qrCodeController.get);
exports.qrCodeRoutes.post('/generate', qrcode_controller_js_1.qrCodeController.generate);
exports.qrCodeRoutes.post('/bulk', qrcode_controller_js_1.qrCodeController.bulk);
exports.qrCodeRoutes.delete('/:id', qrcode_controller_js_1.qrCodeController.remove);
exports.qrCodeRoutes.patch('/:id/status', qrcode_controller_js_1.qrCodeController.status);
